import { createPortal } from 'react-dom';
import { useEffect, useRef, useState } from 'react';
import Icon from '../../components/Icon';
import { reportColumns } from '../columns';
import { DataTable } from '../components/tables';
import { SmartForm } from '../forms/SmartForm';
import { formatDate, formatLogDateTime } from '../lib/format';
import { REPORT_CATALOG, REPORT_CATEGORY_TONES, exportRowsToCsv, reportExportColumns, reportFieldDefs } from '../lib/reports';

export function ReportPreview({ report }) {
  if (!report) {
    return <p className="empty-state">Choose a report type and filters to generate a preview.</p>;
  }

  const rows = report.rows ?? [];
  const columns = reportColumns(rows);

  return (
    <section>
      <div className="report-heading">
        <div>
          <h3>{report.report_type}</h3>
          <p>Generated by {report.generated_by} on {formatDate(report.generated_at)}</p>
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          <button
            className="ghost-button"
            onClick={() => exportRowsToCsv(`${report.report_type.toLowerCase().replaceAll(' ', '-')}.csv`, reportExportColumns(rows), rows)}
            type="button"
          >
            Export CSV
          </button>
          <button className="ghost-button" onClick={() => window.print()} type="button">Print</button>
        </div>
      </div>
      <DataTable columns={columns} rows={rows} />

      {/* Print-only — kept off-screen (see .report-print-view), shown by the
          Print button above. Portaled to <body>, same reasoning as the
          vehicle profile's .veh-print-report: the app's @media print rule
          hides #root entirely, so the printable content has to live outside
          it or Print produces a blank page. */}
      {createPortal(
        <div className="report-print-view">
          <div className="veh-print-header">
            <div className="veh-print-header-left">
              <h2>{report.report_type}</h2>
              <p>Generated by {report.generated_by} on {formatDate(report.generated_at)}</p>
            </div>
            <div className="veh-print-header-right">
              <Icon name="gear" size={48} className="topbar-gear-icon" filled />
              <span className="vms-wordmark">vms</span>
            </div>
          </div>
          <table className="report-print-table">
            <thead>
              <tr>{columns.map((col) => <th key={col.label}>{col.label}</th>)}</tr>
            </thead>
            <tbody>
              {rows.length ? rows.map((row, i) => (
                <tr key={row.id ?? i}>{columns.map((col) => <td key={col.label}>{col.render(row)}</td>)}</tr>
              )) : (
                <tr><td colSpan={columns.length || 1}>No records</td></tr>
              )}
            </tbody>
          </table>
        </div>,
        document.body,
      )}
    </section>
  );
}

export function ReportsModule({ lookups, onGenerate }) {
  // Only one report's form is open at a time, across all categories — same
  // "pick one thing to act on" feel as the reference's report catalog,
  // and it means Generate only ever appears once on screen.
  const [expandedType, setExpandedType] = useState(null);

  return (
    <div className="report-catalog-grid">
      {REPORT_CATALOG.map((group, i) => (
        <section key={group.category} className={`report-category-card tone-${REPORT_CATEGORY_TONES[i % REPORT_CATEGORY_TONES.length]}`}>
          <div className="report-category-card-head">
            <span className="report-category-card-icon"><Icon name={group.icon} size={16} /></span>
            <h4>{group.category}</h4>
            <span className="report-category-count">{group.reports.length}</span>
          </div>
          <div className="report-category-card-body">
            {group.reports.map((r) => {
              const isOpen = expandedType === r.type;
              return (
                <div key={r.type} className={`report-type-row${isOpen ? ' is-open' : ''}`}>
                  <button
                    type="button"
                    className="report-type-item"
                    onClick={() => setExpandedType((t) => (t === r.type ? null : r.type))}
                    aria-expanded={isOpen}
                  >
                    <span className="report-type-icon"><Icon name={r.icon} size={15} /></span>
                    <span className="report-type-text">
                      <strong>{r.type}</strong>
                      <span>{r.description}</span>
                    </span>
                    <Icon name="chevronDown" size={14} className={isOpen ? 'is-expanded' : ''} />
                  </button>
                  {isOpen && (
                    <div className="report-generator-panel">
                      <SmartForm
                        fields={reportFieldDefs(lookups, r)}
                        key={r.type}
                        onSubmit={(values) => onGenerate({ report_type: r.type, ...values })}
                        submitLabel="Generate Report"
                        title=""
                      />
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </section>
      ))}
    </div>
  );
}

// Toolbar button + popover offering a few pre-shaped CSV exports over
// whatever activity rows are currently in view (same filtered/searched set
// the table shows) — a raw chronological dump, and two rollups (by user, by
// module) that are actually useful for "who's been doing what" questions a
// raw log dump doesn't answer directly.
export function GenerateReportButton({ rows }) {
  const [open, setOpen] = useState(false);
  const containerRef = useRef(null);

  useEffect(() => {
    if (!open) return undefined;
    const handleOutsideClick = (e) => {
      if (containerRef.current && !containerRef.current.contains(e.target)) setOpen(false);
    };
    document.addEventListener('mousedown', handleOutsideClick);
    return () => document.removeEventListener('mousedown', handleOutsideClick);
  }, [open]);

  const runReport = (type) => {
    setOpen(false);
    const stamp = new Date().toISOString().slice(0, 10);

    if (type === 'timeline') {
      exportRowsToCsv(`activity-timeline-${stamp}.csv`, [
        { label: 'Date and Time', value: (r) => formatLogDateTime(r.created_at) },
        { label: 'User', value: (r) => r.user?.name ?? 'System' },
        { label: 'Role', value: (r) => r.role ?? '-' },
        { label: 'Module', value: (r) => r.module ?? '-' },
        { label: 'Action', value: (r) => r.action },
        { label: 'Details', value: (r) => r.details ?? '' },
      ], rows);
      return;
    }

    if (type === 'user') {
      const byUser = new Map();
      rows.forEach((r) => {
        const key = r.user?.name ?? 'System';
        const entry = byUser.get(key) ?? { user: key, role: r.role ?? '-', total: 0, last: r.created_at };
        entry.total += 1;
        if (r.created_at && (!entry.last || new Date(r.created_at) > new Date(entry.last))) entry.last = r.created_at;
        byUser.set(key, entry);
      });
      exportRowsToCsv(`activity-by-user-${stamp}.csv`, [
        { label: 'User', value: (r) => r.user },
        { label: 'Role', value: (r) => r.role },
        { label: 'Total Actions', value: (r) => r.total },
        { label: 'Last Active', value: (r) => formatLogDateTime(r.last) },
      ], [...byUser.values()].sort((a, b) => b.total - a.total));
      return;
    }

    if (type === 'module') {
      const byModule = new Map();
      rows.forEach((r) => {
        const key = r.module ?? 'Other';
        byModule.set(key, (byModule.get(key) ?? 0) + 1);
      });
      exportRowsToCsv(`activity-by-module-${stamp}.csv`, [
        { label: 'Module', value: (r) => r.module },
        { label: 'Total Actions', value: (r) => r.total },
      ], [...byModule.entries()].map(([module, total]) => ({ module, total })).sort((a, b) => b.total - a.total));
    }
  };

  return (
    <div className="column-chooser generate-report" ref={containerRef}>
      <button type="button" className={`primary-button generate-report-btn${open ? ' is-active' : ''}`} onClick={() => setOpen((v) => !v)}>
        Generate Report <Icon name="chevronDown" size={13} />
      </button>
      {open && (
        <div className="column-chooser-panel generate-report-panel" role="menu">
          <button type="button" className="generate-report-option" onClick={() => runReport('timeline')}>
            <strong>Timeline Report</strong>
            <span>Every action, in order, exactly as shown below.</span>
          </button>
          <button type="button" className="generate-report-option" onClick={() => runReport('user')}>
            <strong>User Report</strong>
            <span>Action counts per user, most active first.</span>
          </button>
          <button type="button" className="generate-report-option" onClick={() => runReport('module')}>
            <strong>Module Report</strong>
            <span>Action counts per module, busiest first.</span>
          </button>
        </div>
      )}
    </div>
  );
}
